version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mybot
      POSTGRES_USER: umar
      POSTGRES_PASSWORD: 34315454
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"

  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
    build: .
    command: celery -A talkyai worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true

  celery-beat:
    build: .
    command: celery -A talkyai beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true

volumes:
  postgres_data:
  static_volume:
