# Generated by Django 5.0.7 on 2024-08-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='model_name',
            field=models.CharField(default='chatbot', max_length=255),
        ),
    ]
