# Generated by Django 5.0.7 on 2024-08-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_key_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='name',
        ),
    ]
