# Generated by Django 5.0.6 on 2024-08-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_email_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='email_frequency',
            name='last_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
