# Generated by Django 5.0.6 on 2024-08-21 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_email_frequency_last_email_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email_frequency',
            name='last_email_sent_at',
        ),
        migrations.AlterField(
            model_name='email_frequency',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
